### ISSUE TITLE
ActivateModule error

### ISSUE THREAD

**Issue by jimlongo56** [WHMCS/developer-docs#199]
The localApi ActivateModule gives me this error message when using an unsupported moduleType
```
$command = 'ActivateModule';
$postData = array(
    'moduleType' => 'xxx',
    'moduleName' => 'MyModule',
);
$results = localAPI($command, $postData, $adminUsername);
```
```
[message] => Invalid module type provided. Supported module types include: gateway, registrar, addon, fraud
```

So change the moduleType as instructed . . . 
```
$command = 'ActivateModule';
$postData = array(
    'moduleType' => 'addon',
    'moduleName' => 'MyModule',
);
$results = localAPI($command, $postData, $adminUsername);
```
Result is 
```
[message] => Module activation not supported by module type.
```

**Comment by papakai** [comment]
I suggest to report this to WHMCS support, I have my doubts that reporting it here will be considered by their support.

**Comment by WHMCSPeter** [comment]
Hi there!

Typically for issues like this, it is best to reach out directly to our Technical Support team for an expedited resolution.

I can advise that I have been able to reproduce this issue. As such, case #CORE-15458 is open with our developers in order to have this reviewed for future releases. Whilst I cannot provide an estimated time for completion for this, once we resolve cases and push features they are available in our change log at https://changelog.whmcs.com/

I apologize for the inconvenience, and appreciate your patience as we work to resolve this.

Thanks again for taking the time to report your findings.

**Comment by jimlongo56** [comment]
I did open a ticket yesterday, I'll put the number here if I get a response.

**Comment by jimlongo56** [comment]
They opened another case which may be a duplicate of yours. `Case ID CORE-15463`

**Comment by WHMCSPeter** [comment]
No worries. Those cases have been linked and will be reviewed by our Development team. Thanks again for bringing this to our attention. Do feel free to close this issue. We won't be able to attribute any change to this issue here.

Have a great Sunday!
