### ISSUE TITLE
CartItemsTax not working

### ISSUE THREAD

**Issue by dhanda-sunil** [WHMCS/developer-docs#228]
For each cart item CartItemsTax hook called three times, first two times user data not bind, when we get user data on third time, the calculation made on that time are not appearing  in cart or changes not applied. And we need Zipcode the userdata passed, so we can calculate the tax as per zip. From the example we can change price, but changed taxRate not also appearing in Tax Labels, How can we update that too on same time?

**Comment by davidneimeyer** [comment]
If you believe there is a flaw with this hook, please open a support ticket and provide details for reproduction.  This repo is not for support purposes, it is only for suggests of documentation corrections.

- CartItemsTax can be expected to be invoked several time for a page load because re-calculations and validation of cart contents is required.
- Client data be passed if available at that point in runtime.
- Client data will be only available if the User is authenticated and a client account has been selected.
- The zip code is provided in the 'postcode' field.
- You can use 'id' to instantiate a Client model if you require more data about the client.
- This hook only affects the cart total. Use the UpdateInvoice API to manipulate taxes for invoices.
- Manipulation of the display of the tax rate needs to be done through an output hook.  There can be many different ways to express variable, potentially per product, tax rates.  It is beyond the purpose of this hook to accommodate those desires.
