### ISSUE TITLE
UpdateInvoice API

### ISSUE THREAD

**Issue by anupdebnath** [WHMCS/developer-docs#37]
Hello,

Guys I think UpdateInvoice Request Parameter `newitemdescription` `newitemamount` `newitemtaxed` Description Need a update. It only accept array. For example 

`	'newitemdescription' => 'Updated Invoice Item' ,
	'newitemamount' => 100,
	'newitemtaxed' => false`
Code above not work, then i try the following. And it working.
`	'newitemdescription' => array('0' => 'Updated Invoice Item' ),
	'newitemamount' => array('0' => 100 ),
	'newitemtaxed' => false`

**Comment by mattpugh** [comment]
This is correct, the `newitemdescription`, `newitemamount` and `newitemtaxed` parameters are expected to be arrays since they allow you to add multiple line items in a single request. The field types do suggest this but I've opened a case internally to look at clarifying this and perhaps include them in the sample API request.

**Comment by mattpugh** [comment]
@ZizzyZizzy Thanks for letting us know that this is still an issue. I've opened case CORE-13014 to get this revisited and the docs improved.

**Comment by AmiT177** [comment]
This has to be updated...
I've spent hours on it as well, just to find this realizing the example request is wrong
